In [1]:
import pandas as pd
df=pd.read_csv(r'D:\Documentos Mauricio\Desktop\Diplomatura FAMAF2022\Mentoría_Sistema de Transporte Urbano\Practico 3\base_procesada.csv')

In [2]:
df.head(3)

Unnamed: 0  TARJETA  dia_numero  hora  CONTRATO2  SENTIDO_Ida  \
0          24  1000013           2    17          0            0   
1          28  1000017           2    10          6            0   
2          44  1000026           2    14          6            0   

   SENTIDO_Vuelta  LINEA_A  LINEA_A1  LINEA_A600  ...  dia_promedio  \
0               1        0         0           0  ...         101.0   
1               1        0         0           0  ...           2.0   
2               1        0         0           0  ...           2.0   

   cant_lunes  cant_martes  cant_miercoles  cant_jueves  cant_viernes  \
0           2            0               0            0             0   
1           1            0               0            0             0   
2           1            0               0            0             0   

   cant_sabado  cant_domingo  cant_ida  cant_vuelta  
0            0             0         1            1  
1            0             0         0            1  
2            0             0         0            1  

[3 rows x 96 columns]

In [3]:
##BORRAMOS COLUMNAS INNECESARIAS##
df.drop(df.columns[[0, 2, 3,78,79,80,81,82,83,84]], axis=1, inplace=True)

In [4]:
##ESTE VA A SER EL INSUMO PARA APLICAR ML**
df.columns

Index(['TARJETA', 'CONTRATO2', 'SENTIDO_Ida', 'SENTIDO_Vuelta', 'LINEA_A',
       'LINEA_A1', 'LINEA_A600', 'LINEA_A601', 'LINEA_AeroBus', 'LINEA_B',
       'LINEA_B1', 'LINEA_B30', 'LINEA_B60', 'LINEA_B80-Tamse', 'LINEA_C',
       'LINEA_C1', 'LINEA_CAU', 'LINEA_L10', 'LINEA_L11', 'LINEA_L12',
       'LINEA_L13', 'LINEA_L14', 'LINEA_L15', 'LINEA_L16', 'LINEA_L17',
       'LINEA_L18', 'LINEA_L19', 'LINEA_L20', 'LINEA_L22', 'LINEA_L23',
       'LINEA_L24', 'LINEA_L25', 'LINEA_L26', 'LINEA_L27', 'LINEA_L28',
       'LINEA_L29', 'LINEA_L30 C', 'LINEA_L31 T', 'LINEA_L32 T', 'LINEA_L33 T',
       'LINEA_L34 C', 'LINEA_L35 T', 'LINEA_L36 T', 'LINEA_L40 E',
       'LINEA_L41 E', 'LINEA_L42 E', 'LINEA_L43 E', 'LINEA_L44 E', 'LINEA_L45',
       'LINEA_L50', 'LINEA_L51', 'LINEA_L52', 'LINEA_L53', 'LINEA_L54',
       'LINEA_L60', 'LINEA_L61', 'LINEA_L62', 'LINEA_L63', 'LINEA_L64',
       'LINEA_L65', 'LINEA_L66', 'LINEA_L67', 'LINEA_L68', 'LINEA_L70',
       'LINEA_L71', 'LINEA_L72', 'LINEA_L73',

In [5]:
df.describe()

TARJETA      CONTRATO2    SENTIDO_Ida  SENTIDO_Vuelta  \
count  6.980840e+05  698084.000000  698084.000000   698084.000000   
mean   1.349042e+06       4.951158       0.393024        0.606976   
std    2.015196e+05       2.023117       0.488423        0.488423   
min    1.000001e+06       0.000000       0.000000        0.000000   
25%    1.174522e+06       6.000000       0.000000        0.000000   
50%    1.349042e+06       6.000000       0.000000        1.000000   
75%    1.523563e+06       6.000000       1.000000        1.000000   
max    1.698084e+06       6.000000       1.000000        1.000000   

             LINEA_A       LINEA_A1     LINEA_A600     LINEA_A601  \
count  698084.000000  698084.000000  698084.000000  698084.000000   
mean        0.026775       0.036042       0.025092       0.024179   
std         0.161424       0.186394       0.156403       0.153605   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000       0.000000       0.000000   
50%         0.000000       0.000000       0.000000       0.000000   
75%         0.000000       0.000000       0.000000       0.000000   
max         1.000000       1.000000       1.000000       1.000000   

       LINEA_AeroBus        LINEA_B  ...  dia_promedio     cant_lunes  \
count  698084.000000  698084.000000  ...  6.980840e+05  698084.000000   
mean        0.001910       0.067281  ...           inf       3.136025   
std         0.043656       0.250509  ...           NaN       3.697616   
min         0.000000       0.000000  ...  1.000000e+00       0.000000   
25%         0.000000       0.000000  ...  1.347533e+04       0.000000   
50%         0.000000       0.000000  ...  1.590231e+12       2.000000   
75%         0.000000       0.000000  ...  5.359537e+31       5.000000   
max         1.000000       1.000000  ...           inf      75.000000   

         cant_martes  cant_miercoles    cant_jueves   cant_viernes  \
count  698084.000000   698084.000000  698084.000000  698084.000000   
mean        2.551498        1.317876       2.516542       2.549180   
std         3.031674        1.790376       3.045565       3.045783   
min         0.000000        0.000000       0.000000       0.000000   
25%         0.000000        0.000000       0.000000       0.000000   
50%         2.000000        0.000000       2.000000       2.000000   
75%         4.000000        2.000000       4.000000       4.000000   
max        46.000000       24.000000      42.000000      40.000000   

         cant_sabado   cant_domingo       cant_ida    cant_vuelta  
count  698084.000000  698084.000000  698084.000000  698084.000000  
mean        0.005674       0.000046       6.113981       5.962861  
std         0.088394       0.006770       6.873853       6.710046  
min         0.000000       0.000000       0.000000       0.000000  
25%         0.000000       0.000000       1.000000       1.000000  
50%         0.000000       0.000000       3.000000       3.000000  
75%         0.000000       0.000000       9.000000       9.000000  
max         6.000000       1.000000     105.000000     116.000000  

[8 rows x 86 columns]

In [6]:
import numpy as np
r = df.index[np.isinf(df).any(1)]
print(r)
### EN LA FILA 548637 HAY UN VALOR INFINITO##

Int64Index([548637], dtype='int64')


In [7]:
df.replace([np.inf, -np.inf], 0, inplace=True)

In [8]:
##DESPLEGAMOS UN MODELO DE ML PARA PREDECIR LAS CATEGORIAS DE CONTRATO##
##IMPORTAMOS LIBRERIAS
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.metrics import accuracy_score, ConfusionMatrixDisplay, classification_report
from sklearn.tree import DecisionTreeClassifier

In [9]:
y = df.CONTRATO2
X = df.drop('CONTRATO2',axis=1)
X.drop('TARJETA',axis=1,inplace=True)

In [10]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 698084 entries, 0 to 698083
Data columns (total 84 columns):
 #   Column           Non-Null Count   Dtype  
---  ------           --------------   -----  
 0   SENTIDO_Ida      698084 non-null  int64  
 1   SENTIDO_Vuelta   698084 non-null  int64  
 2   LINEA_A          698084 non-null  int64  
 3   LINEA_A1         698084 non-null  int64  
 4   LINEA_A600       698084 non-null  int64  
 5   LINEA_A601       698084 non-null  int64  
 6   LINEA_AeroBus    698084 non-null  int64  
 7   LINEA_B          698084 non-null  int64  
 8   LINEA_B1         698084 non-null  int64  
 9   LINEA_B30        698084 non-null  int64  
 10  LINEA_B60        698084 non-null  int64  
 11  LINEA_B80-Tamse  698084 non-null  int64  
 12  LINEA_C          698084 non-null  int64  
 13  LINEA_C1         698084 non-null  int64  
 14  LINEA_CAU        698084 non-null  int64  
 15  LINEA_L10        698084 non-null  int64  
 16  LINEA_L11        698084 non-null  int6

In [11]:
from sklearn.preprocessing import StandardScaler
x_names = X.columns
X = StandardScaler().fit_transform(X)

C:\Users\Mauricio\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1544: RuntimeWarning: overflow encountered in multiply
  sqr = np.multiply(arr, arr, out=arr)


In [12]:
X = pd.DataFrame(X, columns=x_names)

In [13]:
##DIVIDIMOS LA BASE YA ESTANDARIZADA EN TRAIN Y TEST##
x_train, x_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state = 8)

In [14]:
##PARTIMOS DE UN MODELO DE ARBOL DE CLASIFICACION##
clfs = [DecisionTreeClassifier(random_state=0)]
names = ['Árbol de decisión']

trained_models = []
accuracy_models = []
for clf,name in zip(clfs,names):
    print(name)
    clf.fit(x_train, y_train)
    train_predictions = clf.predict(x_train)
    accuracy = accuracy_score(y_train, train_predictions)
    print(f"Accuracy train {name}: %.2f%%" % (accuracy * 100.0))

    train_predictions = clf.predict(x_test)
    accuracy = accuracy_score(y_test, train_predictions)
    print("Accuracy test {name}: %.2f%%" % (accuracy * 100.0))
    #plot_confusion_matrix(clf,x_test,y_test)
    trained_models.append(clf)
    accuracy_models.append(accuracy*100)

Árbol de decisión
Accuracy train Árbol de decisión: 98.49%
Accuracy test {name}: 65.16%


In [15]:
##AJUSTE DE HIPERPARÁMETROS DE LOS MODELOS ELEGIDOS##
grid = GridSearchCV(DecisionTreeClassifier(random_state=10),
 {'criterion':('gini','entropy'),
 'splitter':("best","random"),
 'max_depth':(10,20,100)})
grid.fit(x_train,y_train)
grid.best_params_


{'criterion': 'entropy', 'max_depth': 10, 'splitter': 'best'}

In [16]:
clf = DecisionTreeClassifier(**grid.best_params_).fit(x_train, y_train)

train_predictions = clf.predict(x_train)
accuracy = accuracy_score(y_train, train_predictions)
print("Accuracy train Arbol de decisión: %.2f%%" % (accuracy * 100.0))

test_predictions = clf.predict(x_test)
accuracy = accuracy_score(y_test, test_predictions)
print("Accuracy test Arbol de decisión: %.2f%%" % (accuracy * 100.0))
#ConfusionMatrixDisplay.from_predictions(y_test, test_predictions)
plt.show()

print(classification_report(y_test,clf.predict(x_test)))


Accuracy train Arbol de decisión: 77.55%
Accuracy test Arbol de decisión: 77.30%
              precision    recall  f1-score   support

           0       0.00      0.00      0.00      6782
           1       0.55      0.20      0.30     16591
           2       0.12      0.00      0.00      1974
           3       0.12      0.00      0.00      2032
           4       0.13      0.00      0.00      3145
           5       0.00      0.00      0.00      2243
           6       0.78      0.98      0.87    106850

    accuracy                           0.77    139617
   macro avg       0.24      0.17      0.17    139617
weighted avg       0.67      0.77      0.70    139617



In [17]:
# Se crea un reporte de clasificación 
from sklearn.metrics import classification_report
crpt= classification_report(y_test, test_predictions, digits=4)
print(crpt)

              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000      6782
           1     0.5486    0.2029    0.2963     16591
           2     0.1176    0.0010    0.0020      1974
           3     0.1250    0.0005    0.0010      2032
           4     0.1316    0.0016    0.0031      3145
           5     0.0000    0.0000    0.0000      2243
           6     0.7838    0.9784    0.8704    106850

    accuracy                         0.7730    139617
   macro avg     0.2438    0.1692    0.1675    139617
weighted avg     0.6715    0.7730    0.7014    139617



In [18]:
FOLDS=5
cv = StratifiedKFold(n_splits=FOLDS, shuffle=True, random_state=10)

x_train2 = np.array(x_train)
y_train2 = np.array(y_train)


for clfi, name in zip([DecisionTreeClassifier(**grid.best_params_)],names):
    print(clfi)
    avg_accuracy = 0
    for fold, (train_idx, val_idx) in enumerate(cv.split(x_train2, y_train2)):
        xi, yi = x_train2[train_idx], y_train2[train_idx]
        x_valid, y_valid = x_train2[val_idx], y_train2[val_idx]
        clfi = clfi.fit(xi, yi)

        test_predictions = clfi.predict(x_valid)
        accuracy = accuracy_score(y_valid, test_predictions)
        avg_accuracy +=accuracy
        print(f"Precisión test fold {fold}: {accuracy * 100.0 :.2f}" % ())

    avg_accuracy /= FOLDS
    print(f'Avg. accuracy = {avg_accuracy * 100}')

DecisionTreeClassifier(criterion='entropy', max_depth=10)
Precisión test fold 0: 77.29
Precisión test fold 1: 77.25
Precisión test fold 2: 77.23
Precisión test fold 3: 77.28
Precisión test fold 4: 77.38
Avg. accuracy = 77.28746735005802


In [19]:
# Se ajusta un modelo de Regresion Logistica
from sklearn.linear_model import SGDClassifier
model = SGDClassifier(loss='log', random_state=0)
model.fit(x_train,y_train)
score = model.score(x_train, y_train)
print("Training score: ", score)

Training score:  0.759606207707886


In [20]:
from sklearn.metrics import confusion_matrix
ypred= model.predict(x_test)
cm= confusion_matrix(y_test, ypred)
print(cm)
###NOTAR QUE EL MODELO ES MUY BUENO PARA PREDECIR EL CONTRATO 6 (GENERAL) Y ES MUY MALO PARA E RESTO DE CATEGORIAS##

[[     0      6      0      0      0      1   6775]
 [     1    610      1      0     12      0  15967]
 [     0    190      2      0     12      1   1769]
 [     0      0      0      0      0      0   2032]
 [     0    109      0      0     35      1   3000]
 [     1     33      0      0      3      0   2206]
 [     5   1287     10      2    112      3 105431]]


In [21]:
# Se crea un reporte de clasificación 
from sklearn.metrics import classification_report
cr= classification_report(y_test, ypred, digits=4)
print(cr)

              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000      6782
           1     0.2729    0.0368    0.0648     16591
           2     0.1538    0.0010    0.0020      1974
           3     0.0000    0.0000    0.0000      2032
           4     0.2011    0.0111    0.0211      3145
           5     0.0000    0.0000    0.0000      2243
           6     0.7686    0.9867    0.8641    106850

    accuracy                         0.7598    139617
   macro avg     0.1995    0.1479    0.1360    139617
weighted avg     0.6273    0.7598    0.6695    139617

